### ISSUE TITLE
The requested operation requires an element of type 'Object', but the target element has type 'Null

### ISSUE THREAD

**Issue by axel845845** [Trollicus/silver-fishstick#4]
This is the error I get, any solution?

![D1](https://github.com/Trollicus/silver-fishstick/assets/84351668/5d9931a5-de08-4b05-992d-dbb58603e13a)

**Comment by IrisV3rm** [comment]
> This is the error I get, any solution?
> 
> ![D1](https://private-user-images.githubusercontent.com/84351668/286057620-5d9931a5-de08-4b05-992d-dbb58603e13a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjY5MDYsIm5iZiI6MTcwMTIyNjYwNiwicGF0aCI6Ii84NDM1MTY2OC8yODYwNTc2MjAtNWQ5OTMxYTUtZGUwOC00YjA1LTk5MmQtZGJiNTg2MDNlMTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAyNTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZjhjZjM1ZDA3ZDU3NWIxODI3NmQ4YmM0NDU4MzA5YzJlODMxYmY5MzhjM2JjNGFiYjRkNDI5N2NlNzQzOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qm6ZJ7A7P97WEEERcC8vDt0QtnI0RR-E3F_X2Y-jUmk)

After looking into it, it appears linkvertise did some more patches and are limiting users to 3 linkvertise links a day, I'll have to look into it when I can

**Comment by IrisV3rm** [comment]
Should be fixed. re-pull and build

**Comment by axel845845** [comment]
But that doesn't solve anything, the limit is still there, there is a website that has been able to evade it, but I don't know how to do it.

**Comment by IrisV3rm** [comment]
> But that doesn't solve anything, the limit is still there, there is a website that has been able to evade it, but I don't know how to do it.

Yes the limit is there but the bypass itself works, you will have to get either residential proxies and or a linkvertise prem account, the way the websites are doing it is they usually cache all requests and have a backlog saved. They also pay for linkvertise premium.

**Comment by AkielStew09** [comment]
I'm getting the same error
